language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

before_script: export NODE_OPTIONS=–max_old_space_size=4096 
script:
  - npm test
  - npm run build

notifications:
  email: true

branches:
  only:
  - master